# Write your MySQL query statement below
WITH A AS (SELECT VISIT_ID FROM TRANSACTIONS)
SELECT CUSTOMER_ID,COUNT(*) AS count_no_trans FROM VISITS WHERE VISIT_ID NOT IN (SELECT VISIT_ID FROM A) GROUP BY CUSTOMER_ID 